### ISSUE TITLE
Error use  angularjs 1.2.7

### ISSUE THREAD

**Issue by ppariona** [CautemocSg/ng-ip-address#8]
I have the following error using version 1.2.7 of angularjs. your help please

"RangeError: Maximum call stack size exceeded
    at https://rawgit.com/CautemocSg/ng-ip-address/master/ngIpAddress.min.js:1:990
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:175:46
    at Array.forEach (<anonymous>)
    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:7:274)
    at c.$setViewValue (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:175:16)
    at https://rawgit.com/CautemocSg/ng-ip-address/master/ngIpAddress.min.js:1:1543
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:175:46
    at Array.forEach (<anonymous>)
    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:7:274)
    at c.$setViewValue (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular.min.js:175:16)"

**Comment by CautemocSg** [comment]
Sorry for the late response, but that should be fixed as of the latest release, version 1.1.13.
